-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:27:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PRODUCTO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'ninguno',
  `precio` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `tlfn` INT(11) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PROVEEDOR` (
  `idPROVEEDOR` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` TEXT(60) NULL,
  `PRODUCTO_codigo` INT NOT NULL,
  PRIMARY KEY (`idPROVEEDOR`),
  INDEX `fk_PROVEEDOR_PRODUCTO1_idx` (`PRODUCTO_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_PROVEEDOR_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo`)
    REFERENCES `ejemplo_producto`.`PRODUCTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`Compra` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`Compra` (
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `PROVEEDOR_idPROVEEDOR` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_idCLIENTE`, `PROVEEDOR_idPROVEEDOR`),
  INDEX `fk_CLIENTE_has_PROVEEDOR_PROVEEDOR1_idx` (`PROVEEDOR_idPROVEEDOR` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PROVEEDOR_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PROVEEDOR_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PROVEEDOR_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_idPROVEEDOR`)
    REFERENCES `ejemplo_producto`.`PROVEEDOR` (`idPROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
